FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY ./scripts/ngrok/main.go .
COPY go.mod go.sum ./
RUN go mod tidy && go build -o tunnel main.go

FROM alpine
WORKDIR /app
COPY --from=builder /app/tunnel .
CMD ["./tunnel"]
